build-job:
  stage: build
  script:
    - echo "Building the image...."
    - docker build -t img:cv-back-v1.1 .
  tags:
    - cv

check:
  stage: test
  script:
    - echo "Here is your images:"
    - docker images
  
  tags:
    - cv

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 2
  tags:
    - cv

deploy-prod:
  stage: deploy
  before_script:
    - cd /app/cvmanager/backend
    - git pull
    - wget 'https://api.s3bucket.cloud/env/.env'
  script:
    - docker compose up -d
  environment: develop
  tags:
    - cv
