stages:
  - build
  - check
  - deploy
  - rollback

variables:
  NODE_ENV: "develop"

before_script:
  - cd /app/cvmanager/backend

build-develop:
  stage: build
  script:
    - echo "Building the image...."
    - docker build --build-arg NODE_ENV=$NODE_ENV -t img:cv-back-latest .
  tags:
    - cv

check:
  stage: check
  script:
    - echo "Here is your images:"
    - docker images | grep "cv-back"
  tags:
    - cv
  needs:
    - build-develop

deploy-develop:
  stage: deploy
  before_script:
    #- git pull
    - wget 'https://api.s3bucket.cloud/env/.env'
    - wget 'https://api.s3bucket.cloud/env/google-application-credentials.json'
         #- wget 'https://api.s3bucket.cloud/env/google-application-credentials.json'
  script:
    - docker compose up -d
  environment: develop
  tags:
    - cv
  when: manual

rollback:
  stage: rollback
  before_script:
    - docker tag img:cv-back-v1.0 img:cv-back-latest
  script:
    - docker compose up -d
  environment: develop
  tags:
    - cv
  when: manual
