stages:
  - build
  - test
  - deploy
  - rollback

#variables:
 # NODE_ENV: "development"

before_script:
  - cd /app/cvmanager/backend
build-develop:
  stage: build
  script:
    - echo "Building the image...."
    - docker build -t img:cv-back-dev .
    # --build-arg NODE_ENV=$NODE_ENV 
  tags:
    - cv
    - beta

test:
  stage: test
  before_script:
    #- git pull
    - cd /app/cvmanager/backend
    - wget -nc 'https://api.s3bucket.cloud/env/.env'
    - wget -nc 'https://api.s3bucket.cloud/env/google-application-credentials.json'
    - wget -nc 'https://api.s3bucket.cloud/env/.env_mongo'
  script:
    - docker compose up -d
  tags:
    - cv
    - beta
  needs:
    - build-develop

deploy-develop:
  stage: deploy
  before_script:
    #- git pull
    - cd /app/cvmanager/backend
    - wget -nc 'https://api.s3bucket.cloud/env/.env'
    - wget -nc 'https://api.s3bucket.cloud/env/google-application-credentials.json'
    - wget -nc 'https://api.s3bucket.cloud/env/.env_mongo'
  script:
    - docker compose up -d
  environment: develop
  tags:
    - cv
    - beta
  when: manual

rollback:
  stage: rollback
  before_script:
    - docker tag img:cv-back-v1.0 img:cv-back-dev
  script:
    - docker compose up -d
  environment: develop
  tags:
    - cv
    - beta
  when: manual
