version: "3.9"

services:

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    volumes:
      - redis_db:/data/myredis

  app:
    container_name: app_container
    build: .
    ports:
      - 4000:8080
    environment:
      PORT: 8080
      JWT_SECRET_TOKEN: 'fdsfdsfasdasdasgffgvfdsbgv'
      JWT_EXPIRATION_TIME_TOKEN: '15m'
      JWT_SECRET_REFRESH_TOKEN: 'dsadasdasdasdasdasdasdasdfdsfds'
      JWT_EXPIRATION_TIME_REFRESH_TOKEN: '30d'
   
      DB_HOST: 'mongo_db'
      DB_PORT: '27017'
      DB_NAME: 'cvmanager'
      DB_USER_NAME: ''
      DB_PASSWORD: ''
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      DEFAULT_LANGUAGE: 'en'
      REDIS_KEY_REF_TOKENS: refTokens
    depends_on:
      - mongo_db
      - redis
volumes:
  mongo_db: {}
  redis_db: {}
