version: "3.9"

services:
  cv_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - cv_app
  cv_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - ./.env
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    depends_on:
      - cv_mongo
      - cv_redis
  cv_mongo:
    restart: always
    image: mongo:4.2.23
    command: mongod --port 27018 
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 'yP6tZ3LwD7VrB'
      MONGO_INITDB_DATABASE: cvmanager
    volumes:
      - ./mongo_db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  cv_redis:
    image: redis:7.0-alpine
    restart: always
    command: --port 6380
    ports:
      - "6380:6380"
    volumes:
      - ./redis_db:/data/myredis
volumes:
  mongo_db: {}
  redis_db: {}
 
