version: "3.9"

services:
  cv_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cv_app
  cv_app:
    build:
      context: .
      args:
        - NODE_ENV=production
    restart: always
    depends_on:
      - cv_mongo
      - cv_redis
  cv_mongo:
    restart: always
    image: mongo:4.2.23
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_DATABASE: 
    volumes:
      - ./mongo_db:/data/db
  cv_redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_db:/data/myredis
volumes:
  mongo_db: {}
  redis_db: {}
 
