version: "3.9"

services:
  
  cv_app:
    #build:
    #  context: .
    #  args:
    #    - NODE_ENV=production
    image: img:cv-back-dev
    container_name: cv_app
    env_file:
      - .env
    hostname: cv_app
    restart: always
    depends_on:
      - cv_mongo
      - cv_redis
    ports:
      - "3080:3080"
    networks:
      - cv_net
    volumes:
      - "./public:/app/backend/public"
      - "./google-application-credentials.json:/app/backend/google-application-credentials.json"
  
  cv_mongo:
    container_name: cv_mongo
    hostname: cv_mongo
    restart: always
    image: mongo:4.2.23
    ports:
      - "27017:27017"
    env_file:
      - .env_mongo 
    volumes:
      - "./mongo_db:/data/db"
    networks:
      - cv_net

  cv_redis:
    container_name: cv_redis
    hostname: cv_redis
    image: redis:6.0.16
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis_db:/data"
    networks:
      - cv_net
      
networks:
  cv_net:
volumes:
  mongo_db: 
  redis_db: 
 
