version: "3.9"

services:
  cv_app:
    container_name: cvmanager_app
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - 4000:8080
    env_file:
      - ./.env
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    depends_on:
      - cv_mongo
      - cv_redis
  cv_mongo:
    container_name: cvmanager_mongo
    restart: always
    image: mongo:4.2.23
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_db:/data/db
  cv_redis:
    container_name: cvmanager_redis
    image: redis:7.0-alpine
    restart: always
    volumes:
      - redis_db:/data/myredis
volumes:
  mongo_db: {}
  redis_db: {}
