name: Rollback

on:    
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Rollback to the last image
        run: |
          chmod +x ./.github/docker_tags
        working-directory: ${{ github.workspace }}
          
          
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Switching to the last image that worked
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/img:$(./.github/docker_tags "${{ secrets.DOCKER_USERNAME }}/img" | sort -V | tail -2 | head -1)
          docker tag ${{ secrets.DOCKER_USERNAME }}/img:$(./.github/docker_tags "${{ secrets.DOCKER_USERNAME }}/img" | sort -V | tail -2 | head -1) ${{ secrets.DOCKER_USERNAME }}/img:back-latest
     
      - name: Push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/img:back-latest
        working-directory: ${{ github.workspace }}
